services:
  emulator:
    build: .
    container_name: emulator_all
    environment:
      - CONFIG=/app/config/base.json
      - MACHINES=100
      - MQTT_HOST=${MQTT_HOST}
      - MQTT_USERNAME=${MQTT_USERNAME}
      - MQTT_PASSWORD=${MQTT_PASSWORD}
      - MQTT_CLIENT_ID=${MQTT_CLIENT_ID}
    volumes:
      - ./config:/app/config:ro
      - ./state:/app/state
